apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: $APPLICATION_NAME
  namespace: argocd
spec:
  project: default
  source:
    repoURL: $REPOSITORY_URL
    targetRevision: HEAD
    path: $TESTS_PATH_IN_REPOSITORY
    plugin:
      name: "testkube-v1.0"
  destination:
    server: https://kubernetes.default.svc
    namespace: $TESTKUBE_NAMESPACE