name: Docker images
on:
    repository_dispatch:
      types: [ trigger-argocd-image-build ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.client_payload.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ github.event.client_payload.release_version }},${{ github.repository }}:latest
          platforms: linux/amd64,linux/arm64
          build-args: |
            VERSION=${{ github.event.client_payload.release_version }}

      - name: Modifiy patch.yaml file with new Tag version
        run: |
          export release_tag=${{ github.event.client_payload.release_version }}
          sed -i "s/\(.*image:.*testkube-argocd.*\:\).*$/\1$release_tag/g" customization/deployment.yaml

      - name: Commit and push changes
        run: |
          git config user.name "kubeshop-bot"
          git config user.email "kubeshop-bot@kubeshop.io"
          git add -A
          git commit -m "New Docker image version is: ${{ github.event.client_payload.release_version }}"
          git push